config/routes.rb
Rails.application.routes.draw do

  resources :contacts, :only => [:index, :show, :new, :create, :destroy]
  resources :errors, :only => [:index]

  namespace :api, defaults: {format: :json} do
       namespace :v1 do
         resources :transactions do
           collection do
             post :verify
           end
         end
         resources :carts
         resources :notifications
         resources :customers
         resources :contacts, :only => [:create]
         resources :registrations do
           collection do
             post :social
             post :profile_image
             post :change_password
           end
         end
         resources :sessions, :only => [:create, :destroy]
         resources :products do
           collection do
             get :real_estate
             get :electronics
             get :phone_and_tablets
             get :automobiles
             get :featured_items
             get :promoted_items
             post :search
           end
         end
       end
  end

  namespace :user do
    resources :profiles
    resources :transactions, :only=> [:index]
    resources :dashboards do
      member do
        post :change_image
        get :wallet_charge
        post :add
      end
    end
    resources :products do
      collection do
        get :approved
        get :unapproved
      end
    end
    resources :tickets do
      member do
        post :add_ticket
      end
    end
    resources :carts do
      member do
        post :add_to_cart
      end
      collection do
        get :empty_cart
        get :check_out
        post :pay
        get :move_next
      end
    end
    resources :notifications do
      member do
        get :select_winner
        get :select_one_option
        get :received
        get :tickets
        get :read
        get :update_notification
      end
    end
    resources :withdraws do
      collection do
        get :request_for_withdraw

      end
    end
  end

  namespace :admin do
    resources :admin_notifications do
      member do
        get :show_all
        get :select_winner
      end
    end
    resources :homes
    resources :requests do
      member do
        get :transfer
      end
    end
    resources :users do
      collection do
        get :all_blocked_users
      end
      member do
        get :block_user
        get :remove_user
        get :product_detail
        get :unblock_user
      end
    end
    resources :products do
      collection do
        get :approved_products
        get :unapproved_products
        get :my_products
        get :select_raffle_items
        get :all_raffle_items
      end
      member do
        get :approve_product
        get :decline_product
        get :mark_raffle
        get :marked_raffle
      end
    end
    resources :promotions
  end

  devise_for :users, path: 'users', controllers: { registrations: 'user/registrations', sessions: 'user/sessions', omniauth_callbacks: 'user/omniauth_callbacks' } #omniauth_callbacks: 'users/omniauth_callbacks'}
  devise_for :admins, path: 'traffle-auth-admins', controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations'}

  resources :newsletters
  resources :homes do
    collection do
      post :search
      get :play
      get :how_to_play
      get :real_estate
      get :electronics
      get :phone_and_tablets
      get :automobiles
      get :featured_items
      get :terms
    end
  end

  authenticated :user do
    root :to => 'homes#index'
  end
  authenticated :admin do
    #root :to => 'admin/stocks#index'
    root :to => 'admin/homes#index'
  end

  root to: 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!
  skip_before_action :authenticate_user_from_token!, :raise => false
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.paginate(:page => params[:page], :per_page => 12)
  end

  def new
    @product = Product.new
    4.times{ @product.images.build }
  end

  def show
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    if admin_signed_in?
      @product.imageable_id = current_admin.id
      @product.imageable_type = "Admin"
      @product.approve = true
    end
    @product_total_tickets = params['product']['price'].to_i / params['product']['ticket_price'].to_i
    @product.total_tickets = @product_total_tickets
    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_products_path(current_user), notice: "Item created Successfully"  }
        format.json { render :show, status: :created, location: @product }
      else
        4.times{ @product.images.build }
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
      @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product_total_tickets = params['product']['price'].to_i / params['product']['ticket_price'].to_i
    @product.total_tickets = @product_total_tickets
    if @product.update(product_params)
       flash[:notice] = "Item has been updated!"
       redirect_to admin_product_path(@product)
    else
       render 'edit'
    end
  end

  def approve_product
    @product = Product.find(params[:id])
    @product.approve = true
    if @product.save
       user_id = @product.imageable_id
       product_id = @product.id
       user = User.where(:id => user_id).select("name").first
       user_name = user.name
       set_noti_description =  user_name + " your Product " + @product.title + " has been approved by admin."

       set_approve_notification = Notification.new(:user_id => user_id, :product_id => product_id, :category => 1, :description => set_noti_description)
       if set_approve_notification.save
         flash[:notice] = "Item Approved Successfully"
         redirect_to unapproved_products_admin_products_path
       end
    else
      flash[:alert] = "Item Not Approved"
      redirect_to admin_product_path(@product.id)
    end
  end

  def decline_product
    @product = Product.find(params[:id])
    @product.approve = nil
    if @product.save
       user_id = @product.imageable_id
       product_id = @product.id
       user = User.where(:id => user_id).select("name").first
       user_name = user.name
       set_noti_description =  user_name + " your Product " + @product.title + " has been decline by admin. Kindly review Your product and submit again."

       set_approve_notification = Notification.new(:user_id => user_id, :product_id => product_id, :category => 5, :description => set_noti_description)
       if set_approve_notification.save
         flash[:notice] = "Item decline Successfully"
         redirect_to root_path
       end
    else

    end
  end


  def approved_products
    @products = Product.where(approve: true).paginate(:page => params[:page], :per_page => 12)
  end

  def unapproved_products
    @products = Product.where(approve: false).paginate(:page => params[:page], :per_page => 12)
  end

  def my_products
    @products = Product.where(imageable_type: "Admin").paginate(:page => params[:page], :per_page => 12)
  end


  def select_raffle_items
    @products = Product.where("sold_tickets < total_tickets AND count_down > ? AND approve = ? AND raffle = ?", Time.current, true, false).order("count_down ASC").paginate(:page => params[:page], :per_page => 12)
  end

  def mark_raffle
    @product = Product.find(params[:id])
  end

  def marked_raffle
    @current_raffle_count = Product.where("sold_tickets < total_tickets AND count_down > ? AND approve = ? AND raffle = ?", Time.current, true, true).count
    @product = Product.find(params[:id])
    if @current_raffle_count < 4
     @product.raffle = true
     @product.save
      flash[:notice] = "The Item is marked as Raffle Successfully!"
     redirect_to select_raffle_items_admin_products_path
   else
     flash[:notice] = "This Item can not be marked Raffle as already 4 items are Raffled"
     redirect_to select_raffle_items_admin_products_path
   end
  end

  def all_raffle_items
    @products = Product.where(:raffle => true)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:category, :title, :total_tickets, :sold_tickets, :short_description, :long_description, :price, :ticket_price,
                                      :approve, :hot, :count_down, :user_id, :admin_id,
                                      images_attributes: [:id, :avatar, :product_id])
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  skip_before_action :authenticate_user_from_token!, :raise => false
  before_action :find_user, only: [:show, :block_user, :remove_user, :unblock_user]
  before_action :find_product, only: [:product_detail]
  def index
    @users = User.where(approve: true)
  end

  def show
    @user_products = @user.products
  end

  def block_user
    @user.approve = false
    @user.save
    flash[:notice] = "User has been blocked by Admin!"
    redirect_to root_path
  end

  def remove_user
    @user.destroy
    flash[:notice] = "User has been removed by Admin!"
    redirect_to root_path
  end

  def all_blocked_users
    @users = User.where(approve: false)
  end

  def unblock_user
    if @user
      @user.approve = true
      @user.save
      flash[:notice] = "User has been UnBlocked!"
      redirect_to root_path
    else
    end
  end

  def product_detail
  end

  private
  def find_user
    @user = User.find(params[:id])
  end

  def find_product
    @product = Product.find(params[:id])
  end
end

app/controllers/user/dashboards_controller.rb
class User::DashboardsController < ApplicationController
  before_action :authenticate_user!
  def show
    @t = current_user.tickets.count
    @e = current_user.tickets.distinct.pluck(:product_id).count
    @p = Product.where(winner_id: current_user.id).count
  end

  def wallet_charge
    if current_user.customer == nil
      redirect_to new_user_dashboard_path
    end
  end

  def new
    @customer = Customer.new
    @user = User.find(current_user.id)
  end

  def add
    paystackObj = Paystack.new(ENV['PAYSTACK_PUBLIC_KEY'], ENV['PAYSTACK_PRIVATE_KEY'])
    amount = params[:amount][:price].to_i
    amount = amount * 100
    transactions = PaystackTransactions.new(paystackObj)
     result = transactions.initializeTransaction(
         :amount => amount,
         :email => current_user.customer.email
       )
       session['access_code'] = result['data']['access_code']
       session['reference'] = result['data']['reference']
       session['payment'] = 1
    @auth_url = result['data']['authorization_url']
  end

  def create
    paystackObj = Paystack.new(ENV['PAYSTACK_PUBLIC_KEY'], ENV['PAYSTACK_PRIVATE_KEY'])
    paystack_customer = PaystackCustomers.new(paystackObj)
    result = paystack_customer.create(
      :first_name => params[:customer][:first_name],
      :last_name =>  params[:customer][:last_name],
      :phone => params[:customer][:phone],
      :email => params[:customer][:email]
    )
    customer = Customer.new(:first_name => params[:customer][:first_name], :last_name => params[:customer][:last_name], :email => params[:customer][:email], :phone => params[:customer][:phone])
    current_user.customer = customer

    redirect_to wallet_charge_user_dashboard_path(1)
  end

  def change_image
    @user = User.find_by_id(params[:id])
    @user.avatar = params[:user][:avatar]
    if @user.save
      flash[:notice] = "Your Image has been changed"
      redirect_to user_dashboard_path(@user.id)
    else
      flash[:notice] = "Your Image has not been changed"
      redirect_to user_dashboard_path(@user.id)
    end
  end
end

app/controllers/user/notifications_controller.rb
class User::NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @notifications = current_user.notifications.order("id DESC")
  end

  def update_notification
    if params[:key].to_i == 1
      update_notification_obj = Notification.find_by_id(params[:id])
      update_notification_obj.read = true
      if update_notification_obj.save
        redirect_to user_product_path(update_notification_obj.product_id)
      end
    elsif params[:key].to_i == 5
      update_notification_obj = Notification.find_by_id(params[:id])
      update_notification_obj.read = true
      if update_notification_obj.save
        redirect_to user_product_path(update_notification_obj.product_id)
      end
    elsif params[:key].to_i == 6
       update_notification_obj = Notification.find_by_id(params[:id])
       redirect_to user_notification_path(update_notification_obj.product_id)
    end
  end

  def update
    if params[:key].to_i == 1
      update_notification_obj = Notification.find_by_id(params[:id])
      update_notification_obj.read = true
      if update_notification_obj.save
        redirect_to user_product_path(update_notification_obj.product_id)
      end
    elsif params[:key].to_i == 5
      update_notification_obj = Notification.find_by_id(params[:id])
      update_notification_obj.read = true
      if update_notification_obj.save
        redirect_to user_product_path(update_notification_obj.product_id)
      end
    elsif params[:key].to_i == 6
       update_notification_obj = Notification.find_by_id(params[:id])
       redirect_to user_notification_path(update_notification_obj.product_id)
    end
  end

  def tickets
    @notification = Notification.find_by_id(params[:id])
    @product = Product.find(@notification.product_id)
    @tickets = @product.tickets
  end

  def select_winner
     @notification = Notification.find_by_id(params[:id])
     product_id = @notification.product_id
     @product = Product.find_by_id(product_id)
     if @product.winner_id == 0
       @product_sold_tickets = @product.sold_tickets
       @tickets = Ticket.where(:product_id => product_id)
       num = Random.new
       @ran = num.rand(0..@product_sold_tickets-1)
       @winner = @tickets[@ran].user

       @winner_id = @winner.id
       @product.winner_id = @winner_id
       @product.save

       update_notification_obj = Notification.find_by_id(params[:id])
       update_notification_obj.read = true
       update_notification_obj.save

       set_description_of_notification = @winner.name + " you WON the prize"
       @notification_to_winner = Notification.new(:user_id => @winner_id, :product_id => product_id, :category => 6, :description => set_description_of_notification)
       @notification_to_winner.save

       #Mailer configuration for Winner
       @winner_profile = User.find_by_id(@winner_id)
       @drawn_product = Product.find_by_id(product_id)
       WinnerMailer.send_mail_to_winner(@winner_profile, @drawn_product).deliver_now

       @tickets = @product.tickets
       @tickets.each do |t|
         @user = t.user
         if @user.id != @winner_profile.id
           WinnerMailer.send_mail_to_other(@user, @drawn_product, @winner_profile).deliver_later!(wait: 1.minute)
         end
       end
       @notification.read = true
       @notification.save
       flash[:notice] = "winner selected Successfully"
     else
       flash[:alert] = "winner for this product is already selected"
       redirect_to root_path
     end
  end

  def select_one_option
    @notification_id = params[:id]
    @notification = Notification.find_by_id(params[:id])
    @notification.read = true
    @notification.save
    @product_id = @notification.product_id
  end

  def show
    @notification = Notification.find(params[:id])
    @product = Product.find(@notification.product_id)
  end

  def received
    @product = Product.find(params[:pid])
    if @product.imageable_type == "User"
      @owner = User.find(@product.imageable_id)
      @total = @product.sold_tickets * @product.ticket_price
      @admin_revenue = @total*0.1
      @owner_revenue = @total - @admin_revenue
      @owner.balance = @owner.balance + @owner_revenue
      @owner.save
      @notification = Notification.find(params[:nid])
      @notification.read = true
      @notification.save
    elsif @product.imageable_type == "Admin"
      @notification = Notification.find(params[:nid])
      @notification.read = true
      @notification.save
    end
    redirect_to root_path
  end

  def read
    @notification = Notification.find(params[:id])
    @notification.read = true
    @notification.save
    redirect_to user_dashboard_path
  end
end

app/controllers/user/profiles_controller.rb
class User::ProfilesController < ApplicationController
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  before_action :auth_user, only: [:new]
  # GET /resource/sign_up
  def new
    super
  end

  protected
    def after_update_path_for(resource)
      edit_user_registration_path()
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/api/v1/products_helper.rb
module Api::V1::ProductsHelper
end

app/helpers/user/carts_helper.rb
module User::CartsHelper
end

app/helpers/user/dashboards_helper.rb
module User::DashboardsHelper
end

app/views/user/products/approved.html.erb
<% content_for :title, "Approved Items | Traffle" %>
<div class="container-fluid" style="background:#F5CBA7;">
  <div class="mainmenu-area">
    <div class="container-fluid">
      <div class="row">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="glyphicon glyphicon-align-justify" style="font-size:33px;color:#BA4A00;"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" style="padding:0px;margin:0px;">
          <ul class="nav navbar-nav" style="padding:0px;margin:0px;float:center;width:100%;margin-left:150px;">
            <li><%= link_to("Home", root_path, class:"my_nav_bar")%></li>
            <li><%= link_to("Real Estate",  real_estate_homes_path, class:"my_nav_bar", onclick:"change(this, 1)")%></li>
            <li><%= link_to("Electronics",  electronics_homes_path, class:"my_nav_bar")%></li>
            <li><%= link_to("Phones and Tablets",  phone_and_tablets_homes_path, class:"my_nav_bar")%></li>
            <li><%= link_to("Automobiles",  automobiles_homes_path, class:"my_nav_bar")%></li>
            <li><%= link_to("Featured Items",  featured_items_homes_path, class:"my_nav_bar")%></li>
            <li><%= link_to("Sell an Item",  new_user_product_path, class:"my_nav_bar")%></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row" >
  <% if notice %>
    <div id="notice_wrapper" class="my_notice">
      <center><p class="app_notice"><%= notice %></p></center>
    </div>
  <%elsif alert %>
    <div id="notice_wrapper" class="my_alert">
      <center><p class="app_alert"><%= alert %></p></center>
    </div>
  <% end %>
</div>
<!--banner-->
<div class="container-fluid">
  <div class="row">
    <center>
      <div class="container">
        <div class="modal fade" id="addPhoto">
          <div class="modal-dialog">
            <div class="modal-content">
              <!-- Header -->
              <div class="modal-header" style="background: #F5CBA7;">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <center><h4 class="heading_text" style="color:white;">Choose Avatar</h4></center>
              </div>
              <!-- Body (form) -->
              <div class="modal-body">
                <div class="form-group">
                  <div class="row">
                    <div class="col-md-12">
                      <center>
                        <%= form_for :user, url: change_image_user_dashboard_path(current_user.id), html: { multipart: true } do |form| %>
                        <%if current_user.avatar.present? %>
                          <%= image_tag (current_user.avatar(:original)),id: 'postimg',class: 'img-responsive img-circle img-thumbnail profile-img', style:"width:200px;height:200px;" %>
                        <%elsif current_user.image_url != nil%>
                          <%= image_tag (current_user.image_url),id: 'postimg',class: 'img-responsive img-circle img-thumbnail profile-img', style:"width:200px;height:200px;" %>
                        <%else %>
                          <%= image_tag ("user.png"),id: 'postimg', class: 'img-responsive img-circle img-thumbnail profile-img', style:"width:200px;height:200px;" %>
                        <%end%>
                        <%= form.file_field :avatar, id:"post-upload",class: "btn btn-info" %>
                        <h4 class="heading_text" style="font-style: italic;color:#2DBF7F;font-weight:normal;">Preview</h4>
                      </center>
                    </div>
                  </div>
                </div>
              </div>
              <div class="modal-footer">
                <div class="row">
                  <div class="col-md-3"></div>
                  <div class="col-md-3">
                    <%= form.submit "Save", class:"btn btn-success btn-block" %>
                  </div>
                  <div class="col-md-3">
                    <button type="button" class="btn btn-danger btn-block" data-dismiss="modal">Close</button>
                  </div>
                  <div class="col-md-3"></div>
                </div>
              <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </center>
  </div>
  <div class="row">
    <%= render 'user/user_panel'%>
    <div class="col-md-9">
      <div class="products">
    		<h2 style="text-align:center;">Approved Items</h2>
        <hr style="background:#BA4A00;height:2px;">
        <div class="col-md-12">
          <% @products.each do |p| %>
            <div class="col-md-6" style="margin-top:15px;">
              <%= render :partial => 'item', locals: {p: p} %>
            </div>
          <% end %>
        </div>
        <center>
          <%= will_paginate @product, renderer: BootstrapPagination::Rails %>
        </center>
      </div>
    </div>
  </div>
</div>
<!-- *************************** Start Script for Uploading Image in Post ************************* -->
<script>
	$(document).ready(function() {
		$("#post-upload").on('change', function() {
			//Get count of selected files
			var countFiles = $(this)[0].files.length;
			var imgPath = $(this)[0].value;
			var extn = imgPath.substring(imgPath.lastIndexOf('.') + 1).toLowerCase();
			var image_holder = $("#postImage-holder");
			image_holder.empty();
			if (extn == "gif" || extn == "png" || extn == "jpg" || extn == "jpeg") {
				if (typeof(FileReader) != "undefined") {
					//loop for each file selected for uploaded.
					for (var i = 0; i < countFiles; i++)
					{
						var reader = new FileReader();
						reader.onload = function(e) {
							$('#postimg').attr('src', e.target.result);

						}
						image_holder.show();
						reader.readAsDataURL($(this)[0].files[i]);
					}
				} else {
					alert("This browser does not support FileReader.");
				}
			}else {
				alert("Please select only images");
			}
		});
	});
</script>
<!-- *************************** End Script for Uploading Image in Post ************************* -->

app/views/user/products/index.html.erb
<% content_for :title, "Items | Traffle" %>
<div class="container-fluid" style="background:#F5CBA7;">
  <div class="mainmenu-area">
    <div class="container-fluid">
      <div class="row">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="glyphicon glyphicon-align-justify" style="font-size:33px;color:#BA4A00;"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" style="padding:0px;margin:0px;">
          <ul class="nav navbar-nav" style="padding:0px;margin:0px;float:center;width:100%;margin-left:150px;">
            <li><%= link_to("Home", root_path, class:"my_nav_bar")%></li>
            <li><%= link_to("Real Estate",  real_estate_homes_path, class:"my_nav_bar", onclick:"change(this, 1)")%></li>
            <li><%= link_to("Electronics",  electronics_homes_path, class:"my_nav_bar")%></li>
            <li><%= link_to("Phones and Tablets",  phone_and_tablets_homes_path, class:"my_nav_bar")%></li>
            <li><%= link_to("Automobiles",  automobiles_homes_path, class:"my_nav_bar")%></li>
            <li><%= link_to("Featured Items",  featured_items_homes_path, class:"my_nav_bar")%></li>
            <li><%= link_to("Sell an Item",  new_user_product_path, class:"my_nav_bar")%></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row" >
  <% if notice %>
    <div id="notice_wrapper" class="my_notice">
      <center><p class="app_notice"><%= notice %></p></center>
    </div>
  <%elsif alert %>
    <div id="notice_wrapper" class="my_alert">
      <center><p class="app_alert"><%= alert %></p></center>
    </div>
  <% end %>
</div>
<!--banner-->
<div class="container-fluid">
  <div class="row">
    <div class="row">
      <center>
        <div class="container">
          <div class="modal fade" id="addPhoto">
            <div class="modal-dialog">
              <div class="modal-content">
                <!-- Header -->
                <div class="modal-header" style="background: #F5CBA7;">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <center><h4 class="heading_text" style="color:white;">Choose Avatar</h4></center>
                </div>
                <!-- Body (form) -->
                <div class="modal-body">
                  <div class="form-group">
                    <div class="row">
                      <div class="col-md-12">
                        <center>
                          <%= form_for :user, url: change_image_user_dashboard_path(current_user.id), html: { multipart: true } do |form| %>
                          <%if current_user.avatar.present? %>
                          <%= image_tag (current_user.avatar(:original)),id: 'postimg',class: 'img-responsive img-circle img-thumbnail profile-img', style:"width:200px;height:200px;" %>
                          <%elsif current_user.image_url != nil%>
                          <%= image_tag (current_user.image_url),id: 'postimg',class: 'img-responsive img-circle img-thumbnail profile-img', style:"width:200px;height:200px;" %>
                          <%else %>
                          <%= image_tag ("user.png"),id: 'postimg', class: 'img-responsive img-circle img-thumbnail profile-img', style:"width:200px;height:200px;" %>
                          <%end%>
                          <%= form.file_field :avatar, id:"post-upload",class: "btn btn-info" %>
                          <h4 class="heading_text" style="font-style: italic;color:#2DBF7F;font-weight:normal;">Preview</h4>
                        </center>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="modal-footer">
                  <div class="row">
                    <div class="col-md-3"></div>
                    <div class="col-md-3">
                      <%= form.submit "Save", class:"btn btn-success btn-block" %>
                    </div>
                    <div class="col-md-3">
                      <button type="button" class="btn btn-danger btn-block" data-dismiss="modal">Close</button>
                    </div>
                    <div class="col-md-3"></div>
                  </div>
                <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </center>
    </div>
    <%= render 'user/user_panel'%>

    <div class="col-md-9">
      <div class="products">
    		<h2 style="text-align:center;">My Items</h2>
        <hr style="background:#BA4A00;height:2px;">
        <div class="col-md-12">
          <% @products.each do |p| %>
            <div class="col-md-6" style="margin-top:15px;">
              <%= render :partial => 'item', locals: {p: p} %>
            </div>
          <% end %>
        </div>
        <center>
          <%= will_paginate @product, renderer: BootstrapPagination::Rails %>
        </center>
      </div>
    </div>
  </div>
</div>
<!-- *************************** Start Script for Uploading Image in Post ************************* -->
<script>
	$(document).ready(function() {
		$("#post-upload").on('change', function() {
			//Get count of selected files
			var countFiles = $(this)[0].files.length;
			var imgPath = $(this)[0].value;
			var extn = imgPath.substring(imgPath.lastIndexOf('.') + 1).toLowerCase();
			var image_holder = $("#postImage-holder");
			image_holder.empty();
			if (extn == "gif" || extn == "png" || extn == "jpg" || extn == "jpeg") {
				if (typeof(FileReader) != "undefined") {
					//loop for each file selected for uploaded.
					for (var i = 0; i < countFiles; i++)
					{
						var reader = new FileReader();
						reader.onload = function(e) {
							$('#postimg').attr('src', e.target.result);

						}
						image_holder.show();
						reader.readAsDataURL($(this)[0].files[i]);
					}
				} else {
					alert("This browser does not support FileReader.");
				}
			}else {
				alert("Please select only images");
			}
		});
	});
</script>
<!-- *************************** End Script for Uploading Image in Post ************************* -->