config/routes.rb
Rails.application.routes.draw do

  resources :contacts, :only => [:index, :show, :new, :create, :destroy]
  resources :errors, :only => [:index]

  namespace :api, defaults: {format: :json} do
       namespace :v1 do
         resources :transactions do
           collection do
             post :verify
           end
         end
         resources :carts
         resources :notifications
         resources :customers
         resources :contacts, :only => [:create]
         resources :registrations do
           collection do
             post :social
             post :profile_image
             post :change_password
           end
         end
         resources :sessions, :only => [:create, :destroy]
         resources :products do
           collection do
             get :real_estate
             get :electronics
             get :phone_and_tablets
             get :automobiles
             get :featured_items
             get :promoted_items
             post :search
           end
         end
       end
  end

  namespace :user do
    resources :profiles
    resources :transactions, :only=> [:index]
    resources :dashboards do
      member do
        post :change_image
        get :wallet_charge
        post :add
      end
    end
    resources :products do
      collection do
        get :approved
        get :unapproved
      end
    end
    resources :tickets do
      member do
        post :add_ticket
      end
    end
    resources :carts do
      member do
        post :add_to_cart
      end
      collection do
        get :empty_cart
        get :check_out
        post :pay
        get :move_next
      end
    end
    resources :notifications do
      member do
        get :select_winner
        get :select_one_option
        get :received
        get :tickets
        get :read
        get :update_notification
      end
    end
    resources :withdraws do
      collection do
        get :request_for_withdraw

      end
    end
  end

  namespace :admin do
    resources :admin_notifications do
      member do
        get :show_all
        get :select_winner
      end
    end
    resources :homes
    resources :requests do
      member do
        get :transfer
      end
    end
    resources :users do
      collection do
        get :all_blocked_users
      end
      member do
        get :block_user
        get :remove_user
        get :product_detail
        get :unblock_user
      end
    end
    resources :products do
      collection do
        get :approved_products
        get :unapproved_products
        get :my_products
        get :select_raffle_items
        get :all_raffle_items
      end
      member do
        get :approve_product
        get :decline_product
        get :mark_raffle
        get :marked_raffle
      end
    end
    resources :promotions
  end

  devise_for :users, path: 'users', controllers: { registrations: 'user/registrations', sessions: 'user/sessions', omniauth_callbacks: 'user/omniauth_callbacks' } #omniauth_callbacks: 'users/omniauth_callbacks'}
  devise_for :admins, path: 'traffle-auth-admins', controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations'}

  resources :newsletters
  resources :homes do
    collection do
      post :search
      get :play
      get :how_to_play
      get :real_estate
      get :electronics
      get :phone_and_tablets
      get :automobiles
      get :featured_items
      get :terms
    end
  end

  authenticated :user do
    root :to => 'homes#index'
  end
  authenticated :admin do
    #root :to => 'admin/stocks#index'
    root :to => 'admin/homes#index'
  end

  root to: 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :imageable, polymorphic: true
  has_many :images
  has_many :tickets
  has_many :carts
  has_many :notifications

  validates :title, presence: true
  validates :title, length: {minimum: 10}
  validates :category, presence: true
  validates :total_tickets, presence: true
  validates :short_description, presence: true
  validates :short_description, length: {minimum: 30}
  validates :long_description, presence: true
  validates :long_description, length: {minimum: 30}
  validates :images, presence: true
  validates :price, presence: true

  validates_datetime :count_down, :after => lambda { Time.current  + 30.days}, on: :create
  accepts_nested_attributes_for :images
  validates_associated :images
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!
  skip_before_action :authenticate_user_from_token!, :raise => false
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.paginate(:page => params[:page], :per_page => 12)
  end

  def new
    @product = Product.new
    4.times{ @product.images.build }
  end

  def show
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    if admin_signed_in?
      @product.imageable_id = current_admin.id
      @product.imageable_type = "Admin"
      @product.approve = true
    end
    @product_total_tickets = params['product']['price'].to_i / params['product']['ticket_price'].to_i
    @product.total_tickets = @product_total_tickets
    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_products_path(current_user), notice: "Item created Successfully"  }
        format.json { render :show, status: :created, location: @product }
      else
        4.times{ @product.images.build }
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
      @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product_total_tickets = params['product']['price'].to_i / params['product']['ticket_price'].to_i
    @product.total_tickets = @product_total_tickets
    if @product.update(product_params)
       flash[:notice] = "Item has been updated!"
       redirect_to admin_product_path(@product)
    else
       render 'edit'
    end
  end

  def approve_product
    @product = Product.find(params[:id])
    @product.approve = true
    if @product.save
       user_id = @product.imageable_id
       product_id = @product.id
       user = User.where(:id => user_id).select("name").first
       user_name = user.name
       set_noti_description =  user_name + " your Product " + @product.title + " has been approved by admin."

       set_approve_notification = Notification.new(:user_id => user_id, :product_id => product_id, :category => 1, :description => set_noti_description)
       if set_approve_notification.save
         flash[:notice] = "Item Approved Successfully"
         redirect_to unapproved_products_admin_products_path
       end
    else
      flash[:alert] = "Item Not Approved"
      redirect_to admin_product_path(@product.id)
    end
  end

  def decline_product
    @product = Product.find(params[:id])
    @product.approve = nil
    if @product.save
       user_id = @product.imageable_id
       product_id = @product.id
       user = User.where(:id => user_id).select("name").first
       user_name = user.name
       set_noti_description =  user_name + " your Product " + @product.title + " has been decline by admin. Kindly review Your product and submit again."

       set_approve_notification = Notification.new(:user_id => user_id, :product_id => product_id, :category => 5, :description => set_noti_description)
       if set_approve_notification.save
         flash[:notice] = "Item decline Successfully"
         redirect_to root_path
       end
    else

    end
  end


  def approved_products
    @products = Product.where(approve: true).paginate(:page => params[:page], :per_page => 12)
  end

  def unapproved_products
    @products = Product.where(approve: false).paginate(:page => params[:page], :per_page => 12)
  end

  def my_products
    @products = Product.where(imageable_type: "Admin").paginate(:page => params[:page], :per_page => 12)
  end


  def select_raffle_items
    @products = Product.where("sold_tickets < total_tickets AND count_down > ? AND approve = ? AND raffle = ?", Time.current, true, false).order("count_down ASC").paginate(:page => params[:page], :per_page => 12)
  end

  def mark_raffle
    @product = Product.find(params[:id])
  end

  def marked_raffle
    @current_raffle_count = Product.where("sold_tickets < total_tickets AND count_down > ? AND approve = ? AND raffle = ?", Time.current, true, true).count
    @product = Product.find(params[:id])
    if @current_raffle_count < 4
     @product.raffle = true
     @product.save
      flash[:notice] = "The Item is marked as Raffle Successfully!"
     redirect_to select_raffle_items_admin_products_path
   else
     flash[:notice] = "This Item can not be marked Raffle as already 4 items are Raffled"
     redirect_to select_raffle_items_admin_products_path
   end
  end

  def all_raffle_items
    @products = Product.where(:raffle => true)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:category, :title, :total_tickets, :sold_tickets, :short_description, :long_description, :price, :ticket_price,
                                      :approve, :hot, :count_down, :user_id, :admin_id,
                                      images_attributes: [:id, :avatar, :product_id])
    end
end

app/controllers/user/products_controller.rb
class User::ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = current_user.products.paginate(:page => params[:page], :per_page => 9)
  end

  def new
    @product = Product.new
    4.times{ @product.images.build }
  end

  def show
    @product = current_user.products.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
    @count =  4
    @count = @count - @product.images.count
    @count.times{ @product.images.build }
  end

  def update
      @product = Product.find(params[:id])
      if @product.approve == nil
        @product.approve = false
      end
      @product_total_tickets = params['product']['price'].to_i / params['product']['ticket_price'].to_i
      @product.total_tickets = @product_total_tickets
      if @product.update(product_params)
         flash[:notice] = "Item has been updated!"
         redirect_to user_products_path
      else
         render 'edit'
      end
  end

  def create
    @product = Product.new(product_params)
    if user_signed_in?
      @product.imageable_id = current_user.id
      @product.imageable_type = "User"
    end
    @product_total_tickets = params['product']['price'].to_i / params['product']['ticket_price'].to_i
    @product.total_tickets = @product_total_tickets
    respond_to do |format|
      if @product.save
        format.html { redirect_to user_dashboard_path(current_user), notice: "Your Product is submitted. You will be notified after Admin approval"  }
        format.json { render :show, status: :created, location: @product }
      else
        4.times{ @product.images.build }
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def approved
    @products = current_user.products.where(approve: true).paginate(:page => params[:page], :per_page => 9)
  end

  def unapproved
    @products = current_user.products.where(approve: false).paginate(:page => params[:page], :per_page => 9)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:category, :title, :total_tickets, :sold_tickets, :short_description, :long_description, :price, :ticket_price,
                                      :approve, :hot, :count_down, :user_id, :admin_id,
                                      images_attributes: [:id, :avatar, :product_id])
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/api/v1/products_helper.rb
module Api::V1::ProductsHelper
end

app/helpers/user/products_helper.rb
module User::ProductsHelper
end

app/views/admin/products/_form.html.erb
<div class="col-md-12">
  <div class="jumbotron" style="padding:0px 0px 0px 0px;background:#11AA99;">
    <%= form_with(model: product, url: admin_products_path, local: true, html: { multipart: true, class:"login", style:"min-width:100%;max-width:100%;padding-bottom:3em;" }) do |f| %>
      <% if controller.action_name == "new" %>
          <p class="title" style="text-align:center;">Add New Item</p>
        <% elsif controller.action_name == "edit" %>
          <p class="title" style="text-align:center;">Edit Item</p>
        <% end %>
        <% if product.errors.any? %>
          <div class="form-group alert alert-error alert-block" id="error_explanation">
            <button type="button" class="close" data-dismiss="alert">x</button>
            <% product.errors.full_messages.each do |message| %>
              <h6 class="heading_error"><%= message%></h6>
            <% end %>
          </div>
        <% end %>
        <div class="row">
          <% count = 1 %>
          <%= f.fields_for :images do |a|%>
            <div class="col-md-3 col-xs-12">
              <center>
                <%= image_tag('add.jpg', id:"product-"+count.to_s, style:"width:100%;height:13em;", class:"img-responsive img-thumbnail")%>
                <%= a.file_field :avatar,class: "btn btn-info btn-sm", style:"width:100%;display:none;", id:"add-product-"+count.to_s  %>
              </center>
            </div>
            <% count = count + 1%>
          <% end %>
        </div>
        <br>
        <div class="row">
          <div class="col-md-4 col-xs-12">
            <%= f.label :category, "Category", class:"label" %><br />
            <%= f.select :category, options_for_select([ "Real Estate", "Electronics", "Phones and Tablets", "Automobiles", "Featured Items"]),{prompt: "Select Item Category"}, {class: 'form-control', style:"font-size: 0.9em;", required: true}%>
          </div>
          <div class="col-md-4 col-xs-12">
            <%= f.label :title, "Title", class:"label" %><br />
            <%= f.text_field :title, autofocus: true, placeholder: 'Item Title  (minimum 10 characters)', class: 'form-control', style:"font-size: 1em;", required: true %>
          </div>
          <div class="col-md-4 col-xs-12">
            <%= f.label :price, "Price", class:"label" %><br />
            <%= f.number_field :price, autofocus: true, placeholder: 'Enter the price of Item', class: 'form-control', style:"font-size: 1em;", required: true, min:"1" %>
          </div>
          <div class="col-md-4 col-xs-12">
            <%= f.label :ticket_price, "Ticket Price", class:"label" %><br />
            <%= f.select :ticket_price, options_for_select([ ["₦ 100", 100],["₦ 200", 200],["₦ 300", 300],["₦ 500", 500],["₦ 1000", 1000],["₦ 3000", 3000],["₦ 5000", 5000],["₦ 10000", 10000]  ]),{prompt: "Select Ticket Price"}, {class: 'form-control', style:"font-size: 0.9em;", required: true}%>
          </div>
          <div class="col-md-4">
          </div>
          <div class="col-md-4">
          </div>
          <div class="col-md-12 col-xs-12">
            <%= f.label :count_down, class: "label" %>
            <br>
            <%= f.datetime_select :count_down, {prompt: true, selected: Date.today, min: 5.days.ago, max: 1.year.from_now}, {class: 'form-control', style:"font-size: 0.8em;width:18.95%;display:inline-block;", required: true}%>
          </div>
          <div class="col-md-6 col-xs-12">
            <%= f.label :short_description, "Short Description", class:"label" %><br />
            <%= f.text_area :short_description, autofocus: true, placeholder: 'Tell people someting about Your item  (minimum 30 characters)', class: 'form-control', size: "4x4", style:"resize: none; font-size: 1em;", required: true %>
          </div>
          <div class="col-md-6 col-xs-12">
            <%= f.label :long_description, "Description", class:"label" %><br />
            <%= f.text_area :long_description, autofocus: true, placeholder: 'Tell people briefly about Your item  (minimum 30 characters)', class: 'form-control', size: "4x4", style:"resize: none; font-size: 1em;", required: true %>
          </div>
        </div>
        <%= f.submit "Save", style:"margin-top:1.2em;"%>
    <%end%>
  </div>
</div>
<!-- *************************** Start Script for Uploading Image in Post ************************* -->
<script>
  $(document).ready(function() {
    $("#product-1").click(function(){
      document.getElementById('add-product-1').click();
    });
    $("#product-2").click(function(){
      document.getElementById('add-product-2').click();
    });
    $("#product-3").click(function(){
      document.getElementById('add-product-3').click();
    });
    $("#product-4").click(function(){
      document.getElementById('add-product-4').click();
    });
    $("#add-product-1").on('change', function() {
      //alert("Hello");
      //console.log("On Change Function Started");
      //Get count of selected files
      var countFiles = $(this)[0].files.length;
      var imgPath = $(this)[0].value;
      var extn = imgPath.substring(imgPath.lastIndexOf('.') + 1).toLowerCase();
      var image_holder = $("#postImage-holder");
      image_holder.empty();
      if (extn == "gif" || extn == "png" || extn == "jpg" || extn == "jpeg") {
        if (typeof(FileReader) != "undefined") {
          //loop for each file selected for uploaded.
          for (var i = 0; i < countFiles; i++)
          {
            var reader = new FileReader();
            reader.onload = function(e) {
              $('#product-1').attr('src', e.target.result);
            }
            image_holder.show();
            reader.readAsDataURL($(this)[0].files[i]);
          }
        } else {
          alert("This browser does not support FileReader.");
        }
      }else {
        alert("Please select only images");
      }
    });
    $("#add-product-2").on('change', function() {
      //alert("Hello");
      //console.log("On Change Function Started");
      //Get count of selected files
      var countFiles = $(this)[0].files.length;
      var imgPath = $(this)[0].value;
      var extn = imgPath.substring(imgPath.lastIndexOf('.') + 1).toLowerCase();
      var image_holder = $("#postImage-holder");
      image_holder.empty();
      if (extn == "gif" || extn == "png" || extn == "jpg" || extn == "jpeg") {
        if (typeof(FileReader) != "undefined") {
          //loop for each file selected for uploaded.
          for (var i = 0; i < countFiles; i++)
          {
            var reader = new FileReader();
            reader.onload = function(e) {
              $('#product-2').attr('src', e.target.result);
            }
            image_holder.show();
            reader.readAsDataURL($(this)[0].files[i]);
          }
        } else {
          alert("This browser does not support FileReader.");
        }
      }else {
        alert("Please select only images");
      }
    });
    $("#add-product-3").on('change', function() {
      //alert("Hello");
      //console.log("On Change Function Started");
      //Get count of selected files
      var countFiles = $(this)[0].files.length;
      var imgPath = $(this)[0].value;
      var extn = imgPath.substring(imgPath.lastIndexOf('.') + 1).toLowerCase();
      var image_holder = $("#postImage-holder");
      image_holder.empty();
      if (extn == "gif" || extn == "png" || extn == "jpg" || extn == "jpeg") {
        if (typeof(FileReader) != "undefined") {
          //loop for each file selected for uploaded.
          for (var i = 0; i < countFiles; i++)
          {
            var reader = new FileReader();
            reader.onload = function(e) {
              $('#product-3').attr('src', e.target.result);
            }
            image_holder.show();
            reader.readAsDataURL($(this)[0].files[i]);
          }
        } else {
          alert("This browser does not support FileReader.");
        }
      }else {
        alert("Please select only images");
      }
    });
    $("#add-product-4").on('change', function() {
      //alert("Hello");
      //console.log("On Change Function Started");
      //Get count of selected files
      var countFiles = $(this)[0].files.length;
      var imgPath = $(this)[0].value;
      var extn = imgPath.substring(imgPath.lastIndexOf('.') + 1).toLowerCase();
      var image_holder = $("#postImage-holder");
      image_holder.empty();
      if (extn == "gif" || extn == "png" || extn == "jpg" || extn == "jpeg") {
        if (typeof(FileReader) != "undefined") {
          //loop for each file selected for uploaded.
          for (var i = 0; i < countFiles; i++)
          {
            var reader = new FileReader();
            reader.onload = function(e) {
              $('#product-4').attr('src', e.target.result);
            }
            image_holder.show();
            reader.readAsDataURL($(this)[0].files[i]);
          }
        } else {
          alert("This browser does not support FileReader.");
        }
      }else {
        alert("Please select only images");
      }
    });
  });
</script>
<!-- *************************** End Script for Uploading Image in Post ************************* -->

app/views/admin/products/approve_product.html.erb
<% content_for :title, "Approve Product | Traffle" %>
<div class="container-fluid" style="padding-top:9em;padding-bottom:2em;">
</div>

app/views/admin/products/mark_raffle.html.erb
<% content_for :title, "Item | Traffle" %>
<div class="container-fluid" style="padding-bottom:5em;padding-top:3em;">
  <div class="row">
    <div class="col-md-12">

      <div class="single">
        <div class="col-md-12">
          <div class="col-md-5 grid col-xs-12">
        		<div class="flexslider">
        			  <ul class="slides">
                  <% @images = @product.images%>
                  <% @images.each do |i|%>
                    <li>
                      <%= image_tag(i.avatar, class:"img-responsive")%>
                    </li>
                  <%end%>
        			  </ul>
        		</div>
        	</div>

          <div class="col-md-7 col-xs-12">
            <div class="row">
              <div class="col-md-12 col-xs-12">
                <center>
                  <h1 class="admin_heading"><%= @product.title%></h1>
                </center>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12 col-xs-12">
                <h4 class="admin_key">Item ID: </h4> <h4 class="admin_value"><%= @product.id%></h4>
              </div>
              <div class="col-md-12 col-xs-12">
                <% @str = @product.created_at.to_s %>
                <% @str = @str.tr('UTC', '')%>
                <h4 class="admin_key">Item Created At: </h4> <h4 class="admin_value"><%= @str %></h4>
              </div>
              <div class="col-md-12 col-xs-12">
                <% @str1 = @product.count_down.to_s %>
                <% @str1 = @str1.tr('UTC', '')%>
                <h4 class="admin_key">Item Valid till: </h4> <h4 class="admin_value"><%= @str1%></h4>
              </div>
              <div class="col-md-12 col-xs-12">
                <h4 class="admin_key">Item Category: </h4> <h4 class="admin_value"><%= @product.category%></h4>
              </div>
              <div class="col-md-12 col-xs-12">
                <h4 class="admin_key">Item Original Price: </h4> <h4 class="admin_value">₦<%= @product.price%></h4>
              </div>
              <div class="col-md-12 col-xs-12">
                <h4 class="admin_key">Item Ticket Price: </h4> <h4 class="admin_value">₦<%= @product.ticket_price%></h4>
              </div>
              <div class="col-md-12 col-xs-12">
                <h4 class="admin_key">Total Tickets: </h4> <h4 class="admin_value"><%= @product.total_tickets %></h4>
              </div>
              <div class="col-md-12 col-xs-12">
                <h4 class="admin_key">Sold Tickets: </h4> <h4 class="admin_value"><%= @product.sold_tickets %></h4>
              </div>
              <br><br>
              <div class="col-md-12">
                <h4 class="admin_key">Item Description: </h4>
              </div>
              <div class="col-md-12">
                <h4 class="admin_value_1" style="margin:0px;"><%= @product.short_description %></h4>
              </div>
              <br><br>
              <div class="col-md-12">
                <h4 class="admin_key">Brief Description: </h4>
              </div>
              <div class="col-md-12">
                <h4 class="admin_value_1" style="margin:0px;"><%= @product.long_description %></h4>
              </div>
            </div>
            <br><br>
            <div class="row">
              <div class="col-md-4">

              </div>
              <div class="col-md-4">
                 <%if @product.raffle == false %>
                    <%= link_to("Raffle It", marked_raffle_admin_product_path(@product.id), class:"btn btn-block btn-success")%>
                 <% end %>
              </div>
              <div class="col-md-4">

              </div>
            </div>

          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<% content_for :title, "Add Item | Traffle" %>
<div class="container-fluid">
  <div class="row">
    <%= render 'form', product: @product %>
  </div>
</div>

app/views/admin/products/select_raffle_items.html.erb
<% content_for :title, "Select Raffle Items | Traffle" %>
<div class="container-fluid" style="padding-bottom:5em;">
  <div class="row">
    <div class="col-md-12">
      <div class="products">
        <h2 style="text-align:center;">Items</h2>
        <hr style="background:#BA4A00;height:2px;">
        <div class="col-md-12">
          <% @products.each do |p|%>
            <div class="col-md-4 col-md4">
              <div class="col-md1 simpleCart_shelfItem">
                <% if p.images[0] %>
                  <%= link_to mark_raffle_admin_product_path(p.id), class:"product_title_display" do %>
                    <%= image_tag(p.images[0].avatar, class:"img-responsive display_image")%>
                    <h4 style="margin-left:7px;"><%= p.title%></h4>
                    <h5 style="margin-left:7px;"><%= p.category%></h5>
                    <h5 style="margin-left:7px;">‎₦<%= p.ticket_price%></h5>
                  <%end%>
                <%end%>
              </div>
            </div>
          <%end%>
        </div>
        <center>
          <%= will_paginate @product, renderer: BootstrapPagination::Rails %>
        </center>
      </div>
    </div>
  </div>

</div>

app/views/admin/products/show.html.erb
<% content_for :title, "Item | Traffle" %>
<div class="container-fluid" style="padding-bottom:5em;padding-top:3em;">
  <div class="row">
    <div class="col-md-12">

      <div class="single">
        <div class="col-md-12">
          <div class="col-md-5 grid col-xs-12">
        		<div class="flexslider">
        			  <ul class="slides">
                  <% @images = @product.images%>
                  <% @images.each do |i|%>
                    <li>
                      <%= image_tag(i.avatar, class:"img-responsive")%>
                    </li>
                  <%end%>
        			  </ul>
        		</div>
        	</div>

          <div class="col-md-7 col-xs-12">
            <div class="row">
              <div class="col-md-12 col-xs-12">
                <center>
                  <h1 class="admin_heading"><%= @product.title%></h1>
                </center>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12 col-xs-12">
                <h4 class="admin_key">Item ID: </h4> <h4 class="admin_value"><%= @product.id%></h4>
              </div>
              <div class="col-md-12 col-xs-12">
                <% @str = @product.created_at.to_s %>
                <% @str = @str.tr('UTC', '')%>
                <h4 class="admin_key">Item Created At: </h4> <h4 class="admin_value"><%= @str %></h4>
              </div>
              <div class="col-md-12 col-xs-12">
                <% @str1 = @product.count_down.to_s %>
                <% @str1 = @str1.tr('UTC', '')%>
                <h4 class="admin_key">Item Valid till: </h4> <h4 class="admin_value"><%= @str1%></h4>
              </div>
              <div class="col-md-12 col-xs-12">
                <h4 class="admin_key">Item Category: </h4> <h4 class="admin_value"><%= @product.category%></h4>
              </div>
              <div class="col-md-12 col-xs-12">
                <h4 class="admin_key">Item Original Price: </h4> <h4 class="admin_value">₦<%= @product.price%></h4>
              </div>
              <div class="col-md-12 col-xs-12">
                <h4 class="admin_key">Item Ticket Price: </h4> <h4 class="admin_value">₦<%= @product.ticket_price%></h4>
              </div>
              <div class="col-md-12 col-xs-12">
                <h4 class="admin_key">Total Tickets: </h4> <h4 class="admin_value"><%= @product.total_tickets %></h4>
              </div>
              <div class="col-md-12 col-xs-12">
                <h4 class="admin_key">Sold Tickets: </h4> <h4 class="admin_value"><%= @product.sold_tickets %></h4>
              </div>
              <br><br>
              <div class="col-md-12">
                <h4 class="admin_key">Item Description: </h4>
              </div>
              <div class="col-md-12">
                <h4 class="admin_value_1" style="margin:0px;"><%= @product.short_description %></h4>
              </div>
              <br><br>
              <div class="col-md-12">
                <h4 class="admin_key">Brief Description: </h4>
              </div>
              <div class="col-md-12">
                <h4 class="admin_value_1" style="margin:0px;"><%= @product.long_description %></h4>
              </div>
            </div>
            <br><br>
            <div class="row">
              <div class="col-md-4">
                <%= link_to("Edit Item", edit_admin_product_path(@product.id), class:"btn btn-block btn-info")%>
              </div>
              <div class="col-md-4">
                <% if @product.approve == false %>
                  <%= link_to("Approve Item", approve_product_admin_product_path(@product.id), class:"btn btn-block btn-success")%>
                <%end%>
              </div>
              <div class="col-md-4">
                <% if @product.approve == false %>
                  <%= link_to("Decline Item", decline_product_admin_product_path(@product.id), class:"btn btn-block btn-danger")%>
                <%end%>
              </div>
            </div>

          </div>
        </div>
      </div>

    </div>
  </div>
</div>