config/routes.rb
Rails.application.routes.draw do

  resources :contacts, :only => [:index, :show, :new, :create, :destroy]
  resources :errors, :only => [:index]

  namespace :api, defaults: {format: :json} do
       namespace :v1 do
         resources :transactions do
           collection do
             post :verify
           end
         end
         resources :carts
         resources :notifications
         resources :customers
         resources :contacts, :only => [:create]
         resources :registrations do
           collection do
             post :social
             post :profile_image
             post :change_password
           end
         end
         resources :sessions, :only => [:create, :destroy]
         resources :products do
           collection do
             get :real_estate
             get :electronics
             get :phone_and_tablets
             get :automobiles
             get :featured_items
             get :promoted_items
             post :search
           end
         end
       end
  end

  namespace :user do
    resources :profiles
    resources :transactions, :only=> [:index]
    resources :dashboards do
      member do
        post :change_image
        get :wallet_charge
        post :add
      end
    end
    resources :products do
      collection do
        get :approved
        get :unapproved
      end
    end
    resources :tickets do
      member do
        post :add_ticket
      end
    end
    resources :carts do
      member do
        post :add_to_cart
      end
      collection do
        get :empty_cart
        get :check_out
        post :pay
        get :move_next
      end
    end
    resources :notifications do
      member do
        get :select_winner
        get :select_one_option
        get :received
        get :tickets
        get :read
        get :update_notification
      end
    end
    resources :withdraws do
      collection do
        get :request_for_withdraw

      end
    end
  end

  namespace :admin do
    resources :admin_notifications do
      member do
        get :show_all
        get :select_winner
      end
    end
    resources :homes
    resources :requests do
      member do
        get :transfer
      end
    end
    resources :users do
      collection do
        get :all_blocked_users
      end
      member do
        get :block_user
        get :remove_user
        get :product_detail
        get :unblock_user
      end
    end
    resources :products do
      collection do
        get :approved_products
        get :unapproved_products
        get :my_products
        get :select_raffle_items
        get :all_raffle_items
      end
      member do
        get :approve_product
        get :decline_product
        get :mark_raffle
        get :marked_raffle
      end
    end
    resources :promotions
  end

  devise_for :users, path: 'users', controllers: { registrations: 'user/registrations', sessions: 'user/sessions', omniauth_callbacks: 'user/omniauth_callbacks' } #omniauth_callbacks: 'users/omniauth_callbacks'}
  devise_for :admins, path: 'traffle-auth-admins', controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations'}

  resources :newsletters
  resources :homes do
    collection do
      post :search
      get :play
      get :how_to_play
      get :real_estate
      get :electronics
      get :phone_and_tablets
      get :automobiles
      get :featured_items
      get :terms
    end
  end

  authenticated :user do
    root :to => 'homes#index'
  end
  authenticated :admin do
    #root :to => 'admin/stocks#index'
    root :to => 'admin/homes#index'
  end

  root to: 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  skip_before_action :authenticate_user_from_token!, :raise => false
  before_action :find_user, only: [:show, :block_user, :remove_user, :unblock_user]
  before_action :find_product, only: [:product_detail]
  def index
    @users = User.where(approve: true)
  end

  def show
    @user_products = @user.products
  end

  def block_user
    @user.approve = false
    @user.save
    flash[:notice] = "User has been blocked by Admin!"
    redirect_to root_path
  end

  def remove_user
    @user.destroy
    flash[:notice] = "User has been removed by Admin!"
    redirect_to root_path
  end

  def all_blocked_users
    @users = User.where(approve: false)
  end

  def unblock_user
    if @user
      @user.approve = true
      @user.save
      flash[:notice] = "User has been UnBlocked!"
      redirect_to root_path
    else
    end
  end

  def product_detail
  end

  private
  def find_user
    @user = User.find(params[:id])
  end

  def find_product
    @product = Product.find(params[:id])
  end
end

app/controllers/api/v1/notifications_controller.rb
class Api::V1::NotificationsController < ApplicationController
  def index
    begin
      @user = User.find_by_email(params[:user_email])
      if @user
        @notifications = Notification.where(:user_id => @user.id).order('id desc')
        render json: {:result => @notifications.as_json()}, status: 200
      else
        render json:  "-1", status: 200
      end
    rescue
      render json:  "-2", status: 200
    end
  end
end

app/controllers/user/carts_controller.rb
class User::CartsController < ApplicationController
  skip_before_action :authenticate_user_from_token!, :only => [:move_next], :raise => false
  before_action :authenticate_user!, :except => [:move_next]
  def index
    @carts = Cart.where(:user_id => current_user.id)
    @no_of_prizes = @carts.count
  end

  def add_to_cart
      price = params[:ticket][:price]
      price = price.to_i
      product_id = params[:id].to_i
      user_id =  current_user.id
      if Product.where("imageable_id = ? AND id = ?", user_id, product_id).first
        flash[:notice] = "You can't buy tickets for this product!"
        redirect_to root_path
      else

        product = Product.find_by(["id = ?", product_id])
        no_of_tickets = price / product.ticket_price
        remaining_tickets = product.total_tickets - product.sold_tickets

        if no_of_tickets <= remaining_tickets
           if Cart.where("user_id = ? AND product_id = ?", user_id, product_id).first
             update_cart = Cart.find_by("user_id = ? AND product_id = ?", user_id, product_id)
             update_cart.total_price = update_cart.total_price + price
             update_cart.save
           else
             new_cart = Cart.new(:user_id => current_user.id, :product_id => product_id, :total_price => price)
             new_cart.save
           end

           flash[:notice] = "Product is Successfully added to your cart!"
           redirect_to user_carts_path
        else
          flash[:alert] = "Only " + remaining_tickets.to_s + " tickets are remaining!"
          if params[:key].to_i == 1
            redirect_to root_path
          elsif params[:key].to_i == 2
            redirect_to real_estate_homes_path
          elsif params[:key].to_i == 3
            redirect_to electronics_homes_path
          elsif params[:key].to_i == 4
            redirect_to phone_and_tablets_homes_path
          elsif params[:key].to_i == 5
            redirect_to automobiles_homes_path
          elsif params[:key].to_i == 6
            redirect_to featured_items_homes_path
          elsif params[:key].to_i == 7
            redirect_to root_path
          elsif params[:key].to_i == 8
            redirect_to root_path
          end
        end
     end
  end


  def destroy
    @carts = Cart.where(:user_id => current_user.id)
    cart = Cart.find(params[:id])
    if cart.destroy
      flash[:notice] = "Item from cart is deleted!"
      redirect_to user_carts_path
    else
      flash[:notice] = "Item from cart is not deleted!"
      redirect_to user_carts_path
    end
  end

  def empty_cart
    @carts = Cart.where(:user_id => current_user.id)
    @count = @carts.count
    if @count != 0
      @carts.each do |f|
        f.destroy
      end
      flash[:notice] = "Your cart has been emptied!"
      redirect_to homes_path
    else
      flash[:notice] = "Your cart is already empty!"
      redirect_to homes_path
    end
  end

  def check_out
    if current_user.customer == nil
      redirect_to new_user_cart_path
    else
      @user_carts = current_user.carts
    end
  end


  def new
    @customer = Customer.new
    @user = User.find(current_user.id)
  end

  def create
    paystackObj = Paystack.new(ENV['PAYSTACK_PUBLIC_KEY'], ENV['PAYSTACK_PRIVATE_KEY'])
    paystack_customer = PaystackCustomers.new(paystackObj)
    result = paystack_customer.create(
      :first_name => params[:customer][:first_name],
      :last_name =>  params[:customer][:last_name],
      :phone => params[:customer][:phone],
      :email => params[:customer][:email]
    )
    customer = Customer.new(:first_name => params[:customer][:first_name], :last_name => params[:customer][:last_name], :email => params[:customer][:email], :phone => params[:customer][:phone])
    current_user.customer = customer

    redirect_to check_out_user_carts_path
  end

  def pay
    if current_user.carts.count > 0
      if params[:amount][:price].to_i == 0
        @carts = current_user.carts
        @total = 0.0
        @carts.each do |c|
          @total = @total + c.total_price
          product_id =  c.product_id
          product = Product.find(product_id)
          @total_tickets = c.total_price / product.ticket_price
          product.sold_tickets = product.sold_tickets + @total_tickets
          product.save
          @total_tickets = @total_tickets.round
          @total_tickets.times{
            tickets_purchased = Ticket.new(:user_id => current_user.id, :product_id => product_id, :price => product.ticket_price)
            tickets_purchased.save
          }
        end
        current_user.carts.destroy_all
        @user = User.find(current_user.id)
        @user.wallet = @user.wallet - @total
        @user.save
        redirect_to user_dashboard_path(current_user)
      else
        paystackObj = Paystack.new(ENV['PAYSTACK_PUBLIC_KEY'], ENV['PAYSTACK_PRIVATE_KEY'])
        amount = params[:amount][:price].to_i
        amount = amount * 100
        transactions = PaystackTransactions.new(paystackObj)
        result = transactions.initializeTransaction(
         :amount => amount,
         :email => current_user.customer.email
        )
        session['access_code'] = result['data']['access_code']
        session['reference'] = result['data']['reference']
        session['payment'] = 0
        @auth_url = result['data']['authorization_url']
      end
    else
      flash[:alert] = "Your Playing cart is empty. Please load Your cart first."
      redirect_to root_path
    end
  end

  def move_next
    if user_signed_in?
      if session['payment'] == 1
        if session['reference'] == params['reference']
          transaction_reference = params['reference']
          paystackObj = Paystack.new(ENV['PAYSTACK_PUBLIC_KEY'], ENV['PAYSTACK_PRIVATE_KEY'])
          transactions = PaystackTransactions.new(paystackObj)
          result = transactions.verify(transaction_reference)
          if result['status'] == true && result['data']['status'] == 'success'
            amount = result['data']['amount'].to_i / 100
            transaction_history = Transaction.new(:reference => result['data']['reference'], :access_code => session['access_code'], :amount => amount, :paystack_transaction_id => result['data']['id'], :user_id => current_user.id)
            transaction_history.save
            @user = User.find(current_user.id)
            @user.wallet = @user.wallet + amount
            @user.save
            flash[:notie] = "Your Transaction is completed!"
            redirect_to user_dashboard_path(current_user)
          else
            flash[:alert] = "Your Transaction is not completed!"
            redirect_to root_path
          end

        else
          flash[:alert] = "Your Transaction is not completed!"
          redirect_to root_path
        end
      elsif session['payment'] == 0
        if session['reference'] == params['reference']
          transaction_reference = params['reference']
          paystackObj = Paystack.new(ENV['PAYSTACK_PUBLIC_KEY'], ENV['PAYSTACK_PRIVATE_KEY'])
      	  transactions = PaystackTransactions.new(paystackObj)
      	  result = transactions.verify(transaction_reference)
          if result['status'] == true && result['data']['status'] == 'success'
             amount = result['data']['amount'].to_i / 100
             transaction_history = Transaction.new(:reference => result['data']['reference'], :access_code => session['access_code'], :amount => amount, :paystack_transaction_id => result['data']['id'], :user_id => current_user.id)
             transaction_history.save
             user_carts = current_user.carts
             user_carts.each do |current_cart|
               product_id =  current_cart.product_id
               product = Product.find(product_id)
               @total_tickets = current_cart.total_price / product.ticket_price
               product.sold_tickets = product.sold_tickets + @total_tickets
               @total_tickets.round
               product.save
               @total_tickets.to_i.times{
                 tickets_purchased = Ticket.new(:user_id => current_user.id, :product_id => product_id, :price => product.ticket_price)
                 tickets_purchased.save
               }
               if product.sold_tickets == product.total_tickets
                 if product.imageable_type == "User"
                   @user = User.find(product.imageable_id)
                   SoldTicketMailer.mail_send_to_product_owner(@user, product).deliver_later!(wait: 1.minute)
                 else
                   @user = Admin.find(product.imageable_id)
                   SoldTicketMailer.mail_send_to_product_owner(@user, product).deliver_later!(wait: 1.minute)
                 end
               end
             end

             @user = User.find(current_user.id)
             @user.wallet = 0
             @user.save
             current_user.carts.destroy_all

             flash[:notice] = "Your Transaction is successfully committed."
             redirect_to user_dashboard_path(current_user)
          else
            flash[:alert] = "Your Transaction is not completed!"
            redirect_to root_path
          end
        else
          flash[:alert] = "Your Transaction is not completed!"
          redirect_to root_path
        end
      end
    else
      redirect_to root_path
    end
  end
end

app/controllers/user/dashboards_controller.rb
class User::DashboardsController < ApplicationController
  before_action :authenticate_user!
  def show
    @t = current_user.tickets.count
    @e = current_user.tickets.distinct.pluck(:product_id).count
    @p = Product.where(winner_id: current_user.id).count
  end

  def wallet_charge
    if current_user.customer == nil
      redirect_to new_user_dashboard_path
    end
  end

  def new
    @customer = Customer.new
    @user = User.find(current_user.id)
  end

  def add
    paystackObj = Paystack.new(ENV['PAYSTACK_PUBLIC_KEY'], ENV['PAYSTACK_PRIVATE_KEY'])
    amount = params[:amount][:price].to_i
    amount = amount * 100
    transactions = PaystackTransactions.new(paystackObj)
     result = transactions.initializeTransaction(
         :amount => amount,
         :email => current_user.customer.email
       )
       session['access_code'] = result['data']['access_code']
       session['reference'] = result['data']['reference']
       session['payment'] = 1
    @auth_url = result['data']['authorization_url']
  end

  def create
    paystackObj = Paystack.new(ENV['PAYSTACK_PUBLIC_KEY'], ENV['PAYSTACK_PRIVATE_KEY'])
    paystack_customer = PaystackCustomers.new(paystackObj)
    result = paystack_customer.create(
      :first_name => params[:customer][:first_name],
      :last_name =>  params[:customer][:last_name],
      :phone => params[:customer][:phone],
      :email => params[:customer][:email]
    )
    customer = Customer.new(:first_name => params[:customer][:first_name], :last_name => params[:customer][:last_name], :email => params[:customer][:email], :phone => params[:customer][:phone])
    current_user.customer = customer

    redirect_to wallet_charge_user_dashboard_path(1)
  end

  def change_image
    @user = User.find_by_id(params[:id])
    @user.avatar = params[:user][:avatar]
    if @user.save
      flash[:notice] = "Your Image has been changed"
      redirect_to user_dashboard_path(@user.id)
    else
      flash[:notice] = "Your Image has not been changed"
      redirect_to user_dashboard_path(@user.id)
    end
  end
end

app/controllers/user/profiles_controller.rb
class User::ProfilesController < ApplicationController
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  before_action :auth_user, only: [:new]
  # GET /resource/sign_up
  def new
    super
  end

  protected
    def after_update_path_for(resource)
      edit_user_registration_path()
    end
end

app/controllers/user/transactions_controller.rb
class User::TransactionsController < ApplicationController
  before_action :authenticate_user!
  def index
    @transactions = current_user.transactions.order("id DESC")
  end
end

app/helpers/api/v1/notifications_helper.rb
module Api::V1::NotificationsHelper
end

app/helpers/user/carts_helper.rb
module User::CartsHelper
end

app/helpers/user/dashboards_helper.rb
module User::DashboardsHelper
end

app/helpers/user/notifications_helper.rb
module User::NotificationsHelper
end

app/helpers/user/products_helper.rb
module User::ProductsHelper
end

app/views/user/notifications/index.html.erb
<% content_for :title, "Dashboard | Traffle" %>
<div class="container-fluid" style="background:#F5CBA7;">
  <div class="mainmenu-area">
    <div class="container-fluid">
      <div class="row">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="glyphicon glyphicon-align-justify" style="font-size:33px;color:#BA4A00;"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" style="padding:0px;margin:0px;">
          <ul class="nav navbar-nav" style="padding:0px;margin:0px;float:center;width:100%;margin-left:150px;">
            <li><%= link_to("Home", root_path, class:"my_nav_bar")%></li>
            <li><%= link_to("Real Estate",  real_estate_homes_path, class:"my_nav_bar", onclick:"change(this, 1)")%></li>
            <li><%= link_to("Electronics",  electronics_homes_path, class:"my_nav_bar")%></li>
            <li><%= link_to("Phones and Tablets",  phone_and_tablets_homes_path, class:"my_nav_bar")%></li>
            <li><%= link_to("Automobiles",  automobiles_homes_path, class:"my_nav_bar")%></li>
            <li><%= link_to("Featured Items",  featured_items_homes_path, class:"my_nav_bar")%></li>
            <li><%= link_to("Sell an Item",  new_user_product_path, class:"my_nav_bar")%></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row" >
  <% if notice %>
    <div id="notice_wrapper" class="my_notice">
      <center><p class="app_notice"><%= notice %></p></center>
    </div>
  <%elsif alert %>
    <div id="notice_wrapper" class="my_alert">
      <center><p class="app_alert"><%= alert %></p></center>
    </div>
  <% end %>
</div>
<!--banner-->
<div class="container-fluid">
  <div class="row">
    <center>
      <div class="container">
        <div class="modal fade" id="addPhoto">
          <div class="modal-dialog">
            <div class="modal-content">
              <!-- Header -->
              <div class="modal-header" style="background: #F5CBA7;">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <center><h4 class="heading_text" style="color:white;">Choose Avatar</h4></center>
              </div>
              <!-- Body (form) -->
              <div class="modal-body">
                <div class="form-group">
                  <div class="row">
                    <div class="col-md-12">
                      <center>
                        <%= form_for :user, url: change_image_user_dashboard_path(current_user.id), html: { multipart: true } do |form| %>
                        <%if current_user.avatar.present? %>
                          <%= image_tag (current_user.avatar(:original)),id: 'postimg',class: 'img-responsive img-circle img-thumbnail profile-img', style:"width:200px;height:200px;" %>
                        <%elsif current_user.image_url != nil%>
                          <%= image_tag (current_user.image_url),id: 'postimg',class: 'img-responsive img-circle img-thumbnail profile-img', style:"width:200px;height:200px;" %>
                        <%else %>
                          <%= image_tag ("user.png"),id: 'postimg', class: 'img-responsive img-circle img-thumbnail profile-img', style:"width:200px;height:200px;" %>
                        <%end%>
                        <%= form.file_field :avatar, id:"post-upload",class: "btn btn-info" %>
                        <h4 class="heading_text" style="font-style: italic;color:#2DBF7F;font-weight:normal;">Preview</h4>
                      </center>
                    </div>
                  </div>
                </div>
              </div>
              <div class="modal-footer">
                <div class="row">
                  <div class="col-md-3"></div>
                  <div class="col-md-3">
                    <%= form.submit "Save", class:"btn btn-success btn-block" %>
                  </div>
                  <div class="col-md-3">
                    <button type="button" class="btn btn-danger btn-block" data-dismiss="modal">Close</button>
                  </div>
                  <div class="col-md-3"></div>
                </div>
              <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </center>
  </div>
  <div class="row">
    <%= render 'user/user_panel' %>
    <div class="col-md-9">
      <div class="jumbotron" style="padding-left:5px;">
        <h4 class="my_text_color" style="text-align:center;">Notifications</h4>
        <ul style="list-style-type:none;width:100%:padding:5px;">
          <%@notifications.each do |n|%>
            <li style="width:100%;color:#BA4A00;border: 1px solid #BA4A00;background:#FFFFFF;padding:10px;"><%= n.description%></li>
          <%end%>
        <ul>
      </div>
    </div>
  </div>
</div>





  <!-- *************************** Start Script for Uploading Image in Post ************************* -->
  <script>
  	$(document).ready(function() {
  		$("#post-upload").on('change', function() {
  			//Get count of selected files
  			var countFiles = $(this)[0].files.length;
  			var imgPath = $(this)[0].value;
  			var extn = imgPath.substring(imgPath.lastIndexOf('.') + 1).toLowerCase();
  			var image_holder = $("#postImage-holder");
  			image_holder.empty();
  			if (extn == "gif" || extn == "png" || extn == "jpg" || extn == "jpeg") {
  				if (typeof(FileReader) != "undefined") {
  					//loop for each file selected for uploaded.
  					for (var i = 0; i < countFiles; i++)
  					{
  						var reader = new FileReader();
  						reader.onload = function(e) {
  							$('#postimg').attr('src', e.target.result);

  						}
  						image_holder.show();
  						reader.readAsDataURL($(this)[0].files[i]);
  					}
  				} else {
  					alert("This browser does not support FileReader.");
  				}
  			}else {
  				alert("Please select only images");
  			}
  		});
  	});
  </script>
  <!-- *************************** End Script for Uploading Image in Post ************************* -->

app/views/user/notifications/select_one_option.html.erb
<% content_for :title, "Select One Option Traffle" %>
<div class="container-fluid" style="background:#F5CBA7;">
  <div class="mainmenu-area">
    <div class="container-fluid">
      <div class="row">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="glyphicon glyphicon-align-justify" style="font-size:33px;color:#BA4A00;"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" style="padding:0px;margin:0px;">
          <ul class="nav navbar-nav" style="padding:0px;margin:0px;float:center;width:100%;margin-left:150px;">
            <li><%= link_to("Home", root_path, class:"my_nav_bar")%></li>
            <li><%= link_to("Real Estate",  real_estate_homes_path, class:"my_nav_bar", onclick:"change(this, 1)")%></li>
            <li><%= link_to("Electronics",  electronics_homes_path, class:"my_nav_bar")%></li>
            <li><%= link_to("Phones and Tablets",  phone_and_tablets_homes_path, class:"my_nav_bar")%></li>
            <li><%= link_to("Automobiles",  automobiles_homes_path, class:"my_nav_bar")%></li>
            <li><%= link_to("Featured Items",  featured_items_homes_path, class:"my_nav_bar")%></li>
            <li><%= link_to("Sell an Item",  new_user_product_path, class:"my_nav_bar")%></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="col-md-9">
  <div class="jumbotron" style="padding: 12em 0px 0px 0px;background:#FFFFFF;margin-left: 15em;">
    <div class="login" style="min-width:100%;max-width:100%;padding-bottom:3em;" >
      <p class="title" style="text-align:center;">Choose One</p>
      <br>
      <div class="row">
        <div class="col-md-12 col-xs-12">
             <div class="row">
               <div class="col-md-5 col-xs-12">
                 <p><center>Edit the product by increasing the count down time so that more tickets can be sold.</center></p>
               </div>
               <div class="col-md-2 col-xs-12">
                 <h2 style="margin-top: 1em;"><center>OR</center></h2>
               </div>
               <div class="col-md-5 col-xs-12">
                 <p><center>Generate a winner</center></p>
               </div>
             </div>
        </div>
        <div class="col-md-12 col-xs-12">
           <div class="col-md-5">
             <center><%= link_to("Edit", edit_user_product_path(@product_id), class:"btn btn-md btn-info") %></center>
           </div>
           <div class="col-md-2">
           </div>
           <div class="col-md-5">
             <center><%= link_to("Winner", select_winner_user_notification_path(@notification_id, key: 3), class:"btn btn-success") %></center>

           </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/user/notifications/show.html.erb
<% content_for :title, "Item Detail | Traffle" %>
<div class="container-fluid" style="background:#F5CBA7;">
  <div class="mainmenu-area">
    <div class="container-fluid">
      <div class="row">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="glyphicon glyphicon-align-justify" style="font-size:33px;color:#BA4A00;"></span>
          </button>
        </div>
        <div class="navbar-collapse collapse" style="padding:0px;margin:0px;">
          <ul class="nav navbar-nav" style="padding:0px;margin:0px;float:center;width:100%;margin-left:150px;">
            <li><%= link_to("Home", root_path, class:"my_nav_bar")%></li>
            <li><%= link_to("Real Estate",  real_estate_homes_path, class:"my_nav_bar", onclick:"change(this, 1)")%></li>
            <li><%= link_to("Electronics",  electronics_homes_path, class:"my_nav_bar")%></li>
            <li><%= link_to("Phones and Tablets",  phone_and_tablets_homes_path, class:"my_nav_bar")%></li>
            <li><%= link_to("Automobiles",  automobiles_homes_path, class:"my_nav_bar")%></li>
            <li><%= link_to("Featured Items",  featured_items_homes_path, class:"my_nav_bar")%></li>
            <li><%= link_to("Sell an Item",  new_user_product_path, class:"my_nav_bar")%></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row" >
  <% if notice %>
    <div id="notice_wrapper" class="my_notice">
      <center><p class="app_notice"><%= notice %></p></center>
    </div>
  <%elsif alert %>
    <div id="notice_wrapper" class="my_alert">
      <center><p class="app_alert"><%= alert %></p></center>
    </div>
  <% end %>
</div>
<div class="container-fluid" style="padding-bottom:5em;padding-top:3em;">
  <div class="row">
    <div class="col-md-12">
      <div class="row">
        <div class="col-md-12">
          <h2><center>You have won this Product</center></h2>
          <br>
        </div>
      </div>
      <div class="single">
        <div class="col-md-12">
          <div class="col-md-5 grid col-xs-12">
        		<div class="flexslider">
        			  <ul class="slides">
                  <% @images = @product.images%>
                  <% @images.each do |i|%>
                    <li>
                      <%= image_tag(i.avatar, class:"img-responsive")%>
                    </li>
                  <%end%>
        			  </ul>
        		</div>
        	</div>

          <div class="col-md-7 col-xs-12">
            <div class="row">
              <div class="col-md-12 col-xs-12">
                <center>
                  <h1 class="admin_heading"><%= @product.title%></h1>
                </center>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12 col-xs-12">
                <h4 class="admin_key">Item ID: </h4> <h4 class="admin_value"><%= @product.id%></h4>
              </div>
              <div class="col-md-12 col-xs-12">
                <h4 class="admin_key">Item Category: </h4> <h4 class="admin_value"><%= @product.category%></h4>
              </div>
              <div class="col-md-12 col-xs-12">
                <h4 class="admin_key">Item Ticket Price: </h4> <h4 class="admin_value">₦<%= @product.ticket_price%></h4>
              </div>
              <br><br>
              <div class="col-md-12">
                <h4 class="admin_key">Item Description: </h4>
              </div>
              <div class="col-md-12">
                <h4 class="admin_value_1" style="margin:0px;"><%= @product.short_description %></h4>
              </div>
              <br><br>
              <div class="col-md-12">
                <h4 class="admin_key">Brief Description: </h4>
              </div>
              <div class="col-md-12">
                <h4 class="admin_value_1" style="margin:0px;"><%= @product.long_description %></h4>
              </div>
            </div>
            <br><br>
            <div class="row">
              <div class="col-md-12 col-xs-12">
                <br><br>
                <center>
                  <%= link_to("I received my Prize", received_user_notification_path(@notification, pid: @product.id, nid: @notification.id), class:"btn btn-block btn-success")%>
                </center>
              </div>
            </div>

          </div>
        </div>
      </div>

    </div>
  </div>
</div>